[variables]
main_domain = "${domain}"
admin_domain = "${domain}"
upload_location = "./data/ghost"
mysql_data_location = "./data/mysql"
ghost_version = "6-alpine"
database_password = "${password:32}"
database_root_password = "${password:32}"
tinybird_admin_token = "${password:32}"
tinybird_workspace_id = "${uuid}"
tinybird_tracker_token = "${password:32}"
tinybird_api_url = "https://api.tinybird.co"

[config]
[[config.domains]]
serviceName = "ghost"
port = 2368
host = "${main_domain}"

[config.env]
DOMAIN = "${main_domain}"
# ADMIN_DOMAIN = "${admin_domain}"
UPLOAD_LOCATION = "${upload_location}"
MYSQL_DATA_LOCATION = "${mysql_data_location}"
GHOST_VERSION = "${ghost_version}"
DATABASE_USER = "ghost"
DATABASE_PASSWORD = "${database_password}"
DATABASE_ROOT_PASSWORD = "${database_root_password}"
TINYBIRD_ADMIN_TOKEN = "${tinybird_admin_token}"
TINYBIRD_WORKSPACE_ID = "${tinybird_workspace_id}"
TINYBIRD_TRACKER_TOKEN = "${tinybird_tracker_token}"
TINYBIRD_API_URL = "${tinybird_api_url}"
ACTIVITYPUB_TARGET = "http://activitypub:8080"

