services:
  openhands:
    image: ${IMAGE:-ghcr.io/all-hands-ai/openhands:latest}
    container_name: openhands-app
    restart: unless-stopped
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE}
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_MOUNT_PATH}
    ports:
      - "3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - openhands_data:/.openhands
      - ${WORKSPACE_PATH}:/opt/workspace_base
    stdin_open: true
    tty: true

volumes:
  openhands_data:
