name = "Plane"
description = "Open-source project management platform"
port = 80

[environment]
PORT = "${PORT}"

# Debug Configuration
DEBUG = "0"
CORS_ALLOWED_ORIGINS = "http://${DOMAIN}"

# Database Configuration
POSTGRES_USER = "plane"
POSTGRES_PASSWORD = "${password:32}"
POSTGRES_DB = "plane"

# Redis Configuration (using Valkey)
REDIS_HOST = "plane-redis"
REDIS_PORT = "6379"

# AWS/MinIO Configuration
AWS_REGION = ""
AWS_ACCESS_KEY_ID = "${base64:16}"
AWS_SECRET_ACCESS_KEY = "${password:32}"
AWS_S3_BUCKET_NAME = "uploads"

# File Upload Configuration
FILE_SIZE_LIMIT = "5242880"

# Application URLs
WEB_URL = "http://${DOMAIN}"

# Worker Configuration
GUNICORN_WORKERS = "2"

# Security Configuration
SECRET_KEY = "${base64:64}"

# RabbitMQ Configuration
RABBITMQ_USER = "plane"
RABBITMQ_PASSWORD = "${password:32}"
RABBITMQ_VHOST = "/"

[domains]
[[domains.main]]
host = "${DOMAIN}"
port = "${PORT}"
path = "/"
