version: '3.8'

services:
  app:
    image: machines/filestash:latest
    restart: always
    environment:
      - APPLICATION_URL=${APPLICATION_URL}
      - CANARY=${CANARY}
      - OFFICE_URL=${OFFICE_URL}
      - OFFICE_FILESTASH_URL=${OFFICE_FILESTASH_URL}
      - OFFICE_REWRITE_URL=${OFFICE_REWRITE_URL}
    ports:
      - 8334
    volumes:
      - filestash:/app/data/state/

  wopi_server:
    image: collabora/code:24.04.10.2.1
    restart: always
    environment:
      # Set below to "true" if you are using custom domain and want to enable SSL
      - extra_params=--o:ssl.enable=false
      - aliasgroup1=https://.*:443
    command:
      - /bin/bash
      - -c
      - |
          curl -o /usr/share/coolwsd/browser/dist/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css
          /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
    user: root
    ports:
      - 9980

volumes:
  filestash: